// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE_GLsP6rcZBF9b7N-wMHwJE3aawyD5lY',
    appId: '1:808499256402:web:dae0da805932730f7a538b',
    messagingSenderId: '808499256402',
    projectId: 'flutter-project-c1ba2',
    authDomain: 'flutter-project-c1ba2.firebaseapp.com',
    storageBucket: 'flutter-project-c1ba2.appspot.com',
    measurementId: 'G-98SZBRZ0RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_6FAg4tlHgXOvwpEEGGYqBZwm-qQrCPA',
    appId: '1:808499256402:android:fdeb46fa80a912aa7a538b',
    messagingSenderId: '808499256402',
    projectId: 'flutter-project-c1ba2',
    storageBucket: 'flutter-project-c1ba2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtw6i8eVc_hgB_RnO1G5ek4A_WrXhlT6I',
    appId: '1:808499256402:ios:d66eeb84ea13a52b7a538b',
    messagingSenderId: '808499256402',
    projectId: 'flutter-project-c1ba2',
    storageBucket: 'flutter-project-c1ba2.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtw6i8eVc_hgB_RnO1G5ek4A_WrXhlT6I',
    appId: '1:808499256402:ios:d66eeb84ea13a52b7a538b',
    messagingSenderId: '808499256402',
    projectId: 'flutter-project-c1ba2',
    storageBucket: 'flutter-project-c1ba2.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE_GLsP6rcZBF9b7N-wMHwJE3aawyD5lY',
    appId: '1:808499256402:web:b11b0cc5fe3780a27a538b',
    messagingSenderId: '808499256402',
    projectId: 'flutter-project-c1ba2',
    authDomain: 'flutter-project-c1ba2.firebaseapp.com',
    storageBucket: 'flutter-project-c1ba2.appspot.com',
    measurementId: 'G-5N72J0XX69',
  );
}
